help:
	@echo "Usage: make [target]"
	@echo "Available targets: welcome clean"

welcome: ./welcome_dir
	@cd welcome_dir && make

clean:
	@cd welcome_dir && make -s clean
	@cd task0 && make -s clean
	@cd task1 && make -s clean
	@cd task2 && make -s clean