help:
	@echo "Usage: make [target]"
	@echo "Available targets: welcome"

welcome: ./welcome_dir
	@cd welcome_dir && make

clean:
	@cd welcome_dir && make clean
	@cd task0 && make clean
	@cd task1 && make clean
	@cd task2 && make clean